#!/bin/bash
clear
echo -e "*****************************************************\n"
echo -e "BIENVENIDO AL PARCHE PROBLEMA DE SONIDO INTEL HDA \n"
echo -e "https://help.ubuntu.com/community/HdaIntelSoundHowto \n"
echo -e "*******************************************************"
RUTA=`pwd`
ID=`id -u`
if [ $ID -ne 0 ]; then
  echo -e 'DEBE EJECUTAR CON SUDO, "sudo ./parcheIntelHDA"'
  exit 1
fi
echo "options snd-hda-intel model=generic" | sudo tee -a /etc/modprobe.d/alsa-base.conf > /dev/null
sleep 1
alsa force-reload
reboot