#!/bin/bash
ARCHIVO=/etc/udev/rules.d/10-network.rules
PREFIJO=`ifconfig | head -n1 | awk {'print $1'} | cut -c 1-3`
NOMBRE=`ifconfig | head -n1 | awk {'print $1'} | cut -c 1-4`
MAC=`ifconfig | grep $PREFIJO | grep HWaddr | awk '{print $5}'`
NOMBRENUEVO="enp1s0"
touch $ARCHIVO
###################################################################################################################################################################################################################
clear
echo -e "************************************\n"
echo -e "BIENVENIDO AL PARCHE TERMINALES MSI \n"
echo -e "**************************************"
RUTA=`pwd`
ID=`id -u`
if [ $ID -ne 0 ]; then
  echo -e "DEBE EJECUTAR CON SUDO, ""sudo """$0
  exit 1
fi
###################################################################################################################################################################################################################
echo
echo -e "SUBSYSTEM==\"net\", ACTION==\"add\", ATTR{address}==\"$MAC\", NAME=\"$NOMBRENUEVO\"" | sudo tee  $ARCHIVO 2>&1 1>/dev/null
echo -e "CONFIGURANDO INTERFACES DE RED -> "$NOMBRE" = "$NOMBRENUEVO
sleep 2
cat /etc/network/interfaces | grep -v $NOMBRE | sudo tee /etc/network/interfaces.bak 2>&1 1>/dev/null
echo -e "auto "$NOMBRENUEVO | sudo tee -a /etc/network/interfaces
echo -e "iface "$NOMBRENUEVO" inet dhcp" | sudo tee -a /etc/network/interfaces
echo -e "CONFIGURANDO SONIDO"
sleep 2
cat /proc/asound/{version,cards,devices,hwdep,pcm,seq/clients}; sudo rm /etc/asound.conf; sudo rm -r ~/.pulse ~/.asound* ; sudo rm ~/.pulse-cookie; sudo apt-get update; sudo apt-get install aptitude; sudo aptitude install paman gnome-alsamixer libasound2-plugins padevchooser libsdl1.2debian-pulseaudio; sudo lshw -short; ls -lart /dev/snd; find /lib/modules/`uname -r` | grep snd ; cat /dev/sndstat; lspci -nn; lsusb; sudo which alsactl;  sudo fuser -v /dev/dsp /dev/snd/* ;  dpkg -S bin/slmodemd; dmesg | egrep 'EMU|probe|emu|ALSA|alsa|ac97|udi|snd|ound|irmware';  sudo /etc/init.d/sl-modem-daemon status; sudo grep model /etc/modprobe.d/* ; sudo dmidecode|egrep 'anufact|roduct|erial|elease'; lsmod | egrep 'snd|usb|midi|udio'; pacmd list-sinks; aplay -l; sudo alsa force-reload; ubuntu-support-status ; sudo lshw -C sound
echo -e "EN 5 SEGUNDOS SE REINICIA LA PC"
sleep 5
reboot